spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatistest?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    hikari:
      username: ndouser
      password: ndopassword
      # >= 8.0: com.mysql.cj.jdbc.Driver
      # <= 8.0: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8010